version: 2

sources:
  - name: Youtube_LLM_Data
    description: "Raw tables from Youtube_LLM"
    database: Youtube_LLM
    schema: RAW
    tables:
      - name: videos
      - name: channels  # Add another table
      - name: comments  # Add another table
      - name: comments_combined # Add another table
      - name: playlist  # Add another table
      

    





    

  