OPENAI_API_KEY = "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"

[connections.snowpark]
user = "ABBASFURNITUREWALA"
password = "Abba$123"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
# Find your account info here:
# https://docs.snowflake.com/en/user-guide/admin-account-identifier
account = "lqeuurc-npb19527"


snowflake_user = 'ABBASFURNITUREWALA'
snowflake_password = 'Abba$123'
snowflake_account = 'lqeuurc-npb19527'
snowflake_database = 'YOUTUBE_LLM'
snowflake_schema = 'RAW'